{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "70e56ef8-af2d-4f68-8f83-c1c560a55f88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded replication dataset: cleaned_full_panel.csv\n",
      "Panel shape: (125, 22)\n",
      "Countries: ['Botswana', 'Malawi', 'Namibia', 'South Africa', 'Tanzania', 'Zambia']\n",
      "Years: 2004 - 2024\n",
      "\n",
      "Summary statistics for core indicators:\n",
      "         mean       std       min       max\n",
      "EAR  0.219986  0.277813  0.000000  1.000000\n",
      "ROA  0.035614  0.073593 -0.035263  0.572277\n",
      "LLR  0.000223  0.002115  0.000000  0.020065\n",
      "LIQ  0.208084  0.243993  0.000000  1.285858\n",
      "WFS  0.105668  0.205094  0.000000  1.990363\n",
      "\n",
      "Missing values in core indicators and lagged predictors:\n",
      "EAR         16\n",
      "ROA         10\n",
      "LLR         35\n",
      "LIQ         35\n",
      "WFS         16\n",
      "EAR_lag1    21\n",
      "ROA_lag1    16\n",
      "LLR_lag1    39\n",
      "LIQ_lag1    39\n",
      "prev_y       6\n",
      "dtype: int64\n",
      "\n",
      "Primary target distribution:\n",
      "y_true\n",
      "0    0.76\n",
      "1    0.24\n",
      "Name: proportion, dtype: float64\n",
      "\n",
      "Alternative target distribution:\n",
      "y_alt\n",
      "0    0.256\n",
      "1    0.744\n",
      "Name: proportion, dtype: float64\n",
      "\n",
      "Stress score distribution:\n",
      "stress_score\n",
      "0    32\n",
      "1    63\n",
      "2    26\n",
      "3     4\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Features used: ['EAR', 'ROA', 'LLR', 'LIQ']\n",
      "\n",
      "=== CORRELATION MATRIX ===\n",
      "          EAR_lag1  ROA_lag1  LLR_lag1  LIQ_lag1\n",
      "EAR_lag1     1.000     0.386    -0.040    -0.105\n",
      "ROA_lag1     0.386     1.000    -0.006     0.108\n",
      "LLR_lag1    -0.040    -0.006     1.000     0.547\n",
      "LIQ_lag1    -0.105     0.108     0.547     1.000\n",
      "\n",
      "=== VARIANCE INFLATION FACTORS ===\n",
      "Variable   VIF\n",
      "EAR_lag1 1.210\n",
      "ROA_lag1 1.218\n",
      "LLR_lag1 1.440\n",
      "LIQ_lag1 1.493\n",
      "\n",
      "OOS dates sample:\n",
      "    country  year\n",
      "0  Botswana  2007\n",
      "1  Botswana  2008\n",
      "2  Botswana  2009\n",
      "3  Botswana  2010\n",
      "4  Botswana  2011\n",
      "\n",
      "Check benchmark equality:\n",
      "NAIVE equals LAG? False\n",
      "\n",
      "=== MAIN MODEL COMPARISON ===\n",
      " Model    Brier  LogLoss     RMSE      AUC       AP   N\n",
      "STRUCT 0.126099 0.396610 0.355105 0.831781 0.590155 107\n",
      "HYBRID 0.145202 0.448605 0.381053 0.771222 0.424775 107\n",
      " NAIVE 0.177634 0.541687 0.421466 0.527174 0.230139 107\n",
      "   LAG 0.186916 2.582339 0.432337 0.738872 0.424982 107\n",
      " LOGIT 0.203773 0.617789 0.451413 0.577122 0.277744 107\n",
      "\n",
      "=== SUPPLEMENTARY MODEL COMPARISON WITH CALIBRATED HYBRID ===\n",
      "     Model    Brier  LogLoss     RMSE      AUC       AP   N\n",
      "    STRUCT 0.126099 0.396610 0.355105 0.831781 0.590155 107\n",
      "    HYBRID 0.145202 0.448605 0.381053 0.771222 0.424775 107\n",
      "     NAIVE 0.177634 0.541687 0.421466 0.527174 0.230139 107\n",
      "HYBRID_CAL 0.179166 0.559496 0.423280 0.648033 0.287180 107\n",
      "       LAG 0.186916 2.582339 0.432337 0.738872 0.424982 107\n",
      "     LOGIT 0.203773 0.617789 0.451413 0.577122 0.277744 107\n",
      "\n",
      "=== HYBRID PARAMETERS - FULL OOS FIT FOR REPORTING ===\n",
      "{'mode': 'offset_glm_cv', 'a': -0.30965182099339933, 'w': 0.19788959117135818}\n",
      "\n",
      "=== POOLED BOOTSTRAP AUC COMPARISONS ===\n",
      "STRUCT vs LOGIT {'mean_diff': 0.25763364102971925, 'ci_lower': 0.11059220298964885, 'ci_upper': 0.42455095193508113, 'n_boot_used': 1000}\n",
      "STRUCT vs HYBRID {'mean_diff': 0.060698237980181986, 'ci_lower': 0.025746763181738623, 'ci_upper': 0.09566069013937996, 'n_boot_used': 1000}\n",
      "LOGIT vs HYBRID {'mean_diff': -0.19693540304953727, 'ci_lower': -0.35620096176565447, 'ci_upper': -0.04753408273878664, 'n_boot_used': 1000}\n",
      "NAIVE vs LAG {'mean_diff': -0.2148666449557617, 'ci_lower': -0.3740036231884056, 'ci_upper': -0.0453656291834003, 'n_boot_used': 1000}\n",
      "\n",
      "=== WoE ROBUSTNESS RESULTS ===\n",
      "               Model    Brier  LogLoss      AUC       AP   N\n",
      "Raw continuous logit 0.203773 0.617789 0.577122 0.277744 107\n",
      "    WoE-binned logit 0.149270 0.465904 0.765787 0.533204 107\n",
      " Structural baseline 0.126099 0.396610 0.831781 0.590155 107\n",
      "              Hybrid 0.145202 0.448605 0.771222 0.424775 107\n",
      "\n",
      "=== WoE COEFFICIENT SUMMARY ===\n",
      "    Variable      Mean  Std. Dev. Sign\n",
      "EAR_lag1_woe -0.952801   0.325390    -\n",
      "ROA_lag1_woe -0.456380   0.182088    -\n",
      "LLR_lag1_woe  0.000000   0.000000    +\n",
      "LIQ_lag1_woe -0.546976   0.365021    -\n",
      "\n",
      "Saved table outputs to: outputs\n",
      "Probability distribution figure saved to: figures\\probability_distributions.png\n",
      "Calibration curve saved to: figures\\appendix_calibration_curve.png\n",
      "Coefficient paths figure saved to: figures\\appendix_coefficient_paths.png\n",
      "Country-level probability trajectories saved to: figures\\country_probability_trajectories.png\n",
      "Pooled probability signals figure saved to: figures\\appendix_pooled_probability_signals.png\n",
      "\n",
      "=== FINAL BOOTSTRAP AUC DIFFERENCE TABLE ===\n",
      "      Comparison  Mean Diff.  Lower CI  Upper CI  n_boot_used\n",
      " STRUCT vs LOGIT       0.258     0.111     0.425         1000\n",
      "STRUCT vs HYBRID       0.061     0.026     0.096         1000\n",
      " LOGIT vs HYBRID      -0.197    -0.356    -0.048         1000\n",
      "    NAIVE vs LAG      -0.215    -0.374    -0.045         1000\n",
      "Bootstrap mean-difference table saved to: outputs\\bootstrap_auc_mean_differences.csv\n",
      "\n",
      "Replication script completed successfully.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import random\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import statsmodels.api as sm\n",
    "from statsmodels.stats.outliers_influence import variance_inflation_factor\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from scipy.special import expit\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import (\n",
    "    log_loss,\n",
    "    roc_auc_score,\n",
    "    roc_curve,\n",
    "    auc,\n",
    "    precision_recall_curve,\n",
    "    average_precision_score,\n",
    "    brier_score_loss,\n",
    ")\n",
    "\n",
    "from sklearn.isotonic import IsotonicRegression\n",
    "from sklearn.calibration import calibration_curve\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 1. SETTINGS\n",
    "# =========================================================\n",
    "\n",
    "RANDOM_STATE = 42\n",
    "np.random.seed(RANDOM_STATE)\n",
    "random.seed(RANDOM_STATE)\n",
    "os.environ[\"PYTHONHASHSEED\"] = str(RANDOM_STATE)\n",
    "\n",
    "DATA_FILE = \"cleaned_full_panel.csv\"\n",
    "OUTPUT_DIR = \"outputs\"\n",
    "FIG_DIR = \"figures\"\n",
    "\n",
    "WARMUP_YEARS = 3\n",
    "\n",
    "STRUCT_ALPHA = 0.50\n",
    "STRUCT_K = 2.0\n",
    "EPS = 1e-6\n",
    "\n",
    "# Choose \"y_true\" for primary target or \"y_alt\" for alternative target.\n",
    "TARGET_COL = \"y_true\"\n",
    "\n",
    "# Calibration is supplementary; main table should use p_hybrid_cv.\n",
    "USE_ISOTONIC = True\n",
    "ISO_BLEND = 0.10\n",
    "\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "os.makedirs(FIG_DIR, exist_ok=True)\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 2. HELPERS\n",
    "# =========================================================\n",
    "\n",
    "def safe_prob(p, eps=EPS):\n",
    "    return np.clip(np.asarray(p, dtype=float), eps, 1.0 - eps)\n",
    "\n",
    "\n",
    "def safe_logit(p, eps=EPS):\n",
    "    p = safe_prob(p, eps=eps)\n",
    "    return np.log(p) - np.log1p(-p)\n",
    "\n",
    "\n",
    "def sigmoid(z):\n",
    "    return expit(z)\n",
    "\n",
    "\n",
    "def valid_xy(df, y_col, p_col):\n",
    "    tmp = df[[y_col, p_col]].dropna().copy()\n",
    "    return tmp[y_col].astype(int).values, tmp[p_col].astype(float).values\n",
    "\n",
    "\n",
    "def make_logit_pipeline():\n",
    "    return make_pipeline(\n",
    "        SimpleImputer(strategy=\"median\"),\n",
    "        StandardScaler(),\n",
    "        LogisticRegression(\n",
    "            penalty=\"l2\",\n",
    "            solver=\"lbfgs\",\n",
    "            max_iter=1000,\n",
    "            random_state=RANDOM_STATE,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "\n",
    "def compare_models(oos, target_col=\"y_true\", include_calibrated=False):\n",
    "    rows = []\n",
    "    y = oos[target_col].astype(int).values\n",
    "\n",
    "    model_cols = [\n",
    "        (\"p_struct\", \"STRUCT\"),\n",
    "        (\"p_logit\", \"LOGIT\"),\n",
    "        (\"p_hybrid_cv\", \"HYBRID\"),\n",
    "        (\"p_naive\", \"NAIVE\"),\n",
    "        (\"p_lag\", \"LAG\"),\n",
    "    ]\n",
    "\n",
    "    if include_calibrated:\n",
    "        model_cols.insert(3, (\"p_hybrid_cv_cal\", \"HYBRID_CAL\"))\n",
    "\n",
    "    for col, label in model_cols:\n",
    "        if col not in oos.columns:\n",
    "            continue\n",
    "\n",
    "        p = safe_prob(oos[col].astype(float).values)\n",
    "        mask = ~np.isnan(p) & ~np.isnan(y)\n",
    "\n",
    "        if not np.any(mask):\n",
    "            continue\n",
    "\n",
    "        y_m = y[mask]\n",
    "        p_m = p[mask]\n",
    "\n",
    "        brier = np.mean((p_m - y_m) ** 2)\n",
    "        rmse = np.sqrt(brier)\n",
    "        ll = log_loss(y_m, p_m, labels=[0, 1])\n",
    "\n",
    "        if np.unique(y_m).size > 1:\n",
    "            auc_val = roc_auc_score(y_m, p_m)\n",
    "            ap = average_precision_score(y_m, p_m)\n",
    "        else:\n",
    "            auc_val = 0.5\n",
    "            ap = y_m.mean()\n",
    "\n",
    "        rows.append([label, brier, ll, rmse, auc_val, ap, int(mask.sum())])\n",
    "\n",
    "    out = pd.DataFrame(\n",
    "        rows,\n",
    "        columns=[\"Model\", \"Brier\", \"LogLoss\", \"RMSE\", \"AUC\", \"AP\", \"N\"],\n",
    "    )\n",
    "\n",
    "    return out.sort_values(\"Brier\").reset_index(drop=True)\n",
    "\n",
    "\n",
    "def make_oos_dates(df, warmup=3):\n",
    "    rows = []\n",
    "\n",
    "    for c, g in df.groupby(\"country\"):\n",
    "        yrs = np.sort(g[\"year\"].dropna().unique())\n",
    "\n",
    "        if len(yrs) > warmup:\n",
    "            rows.append(pd.DataFrame({\"country\": c, \"year\": yrs[warmup:]}))\n",
    "\n",
    "    if rows:\n",
    "        return pd.concat(rows, ignore_index=True)\n",
    "\n",
    "    return pd.DataFrame(columns=[\"country\", \"year\"])\n",
    "\n",
    "# =========================================================\n",
    "# 3. BENCHMARK MODELS\n",
    "# =========================================================\n",
    "\n",
    "def compute_naive_prob(df, country, year, target_col=\"y_true\"):\n",
    "    \"\"\"\n",
    "    NAIVE benchmark:\n",
    "    Pooled historical prevalence using only information before forecast year.\n",
    "    \"\"\"\n",
    "    hist = df[df[\"year\"] < year].copy()\n",
    "\n",
    "    if hist.empty:\n",
    "        prior = df[target_col].mean()\n",
    "    else:\n",
    "        prior = hist[target_col].mean()\n",
    "\n",
    "    if pd.isna(prior):\n",
    "        prior = 0.5\n",
    "\n",
    "    return float(safe_prob(prior))\n",
    "\n",
    "\n",
    "def compute_lag_prob(df, country, year, target_col=\"y_true\"):\n",
    "    \"\"\"\n",
    "    LAG benchmark:\n",
    "    p_lag_{it} = y_{i,t-1}, clipped only for numerical stability.\n",
    "    \"\"\"\n",
    "    row = df[(df[\"country\"] == country) & (df[\"year\"] == year)]\n",
    "\n",
    "    if row.empty:\n",
    "        return np.nan\n",
    "\n",
    "    prev_target = row[\"prev_target\"].iloc[0]\n",
    "\n",
    "    if pd.notna(prev_target):\n",
    "        return float(safe_prob(prev_target))\n",
    "\n",
    "    hist = df[df[\"year\"] < year]\n",
    "    prior = hist[target_col].mean()\n",
    "\n",
    "    if pd.isna(prior):\n",
    "        prior = 0.5\n",
    "\n",
    "    return float(safe_prob(prior))\n",
    "\n",
    "def bootstrap_auc_diff(y, p1, p2, n_boot=1000, random_state=42):\n",
    "    \"\"\"\n",
    "    Pooled nonparametric bootstrap for AUC differences.\n",
    "    \"\"\"\n",
    "    rng = np.random.default_rng(random_state)\n",
    "    diffs = []\n",
    "    n = len(y)\n",
    "\n",
    "    for _ in range(n_boot):\n",
    "        idx = rng.choice(n, size=n, replace=True)\n",
    "        y_b = y[idx]\n",
    "\n",
    "        if len(np.unique(y_b)) < 2:\n",
    "            continue\n",
    "\n",
    "        auc1 = roc_auc_score(y_b, p1[idx])\n",
    "        auc2 = roc_auc_score(y_b, p2[idx])\n",
    "        diffs.append(auc1 - auc2)\n",
    "\n",
    "    diffs = np.asarray(diffs)\n",
    "\n",
    "    if len(diffs) == 0:\n",
    "        return {\n",
    "            \"mean_diff\": np.nan,\n",
    "            \"ci_lower\": np.nan,\n",
    "            \"ci_upper\": np.nan,\n",
    "            \"n_boot_used\": 0,\n",
    "        }\n",
    "\n",
    "    return {\n",
    "        \"mean_diff\": float(np.mean(diffs)),\n",
    "        \"ci_lower\": float(np.percentile(diffs, 2.5)),\n",
    "        \"ci_upper\": float(np.percentile(diffs, 97.5)),\n",
    "        \"n_boot_used\": int(len(diffs)),\n",
    "    }\n",
    "\n",
    "# =========================================================\n",
    "# 4. LOAD CLEANED REPLICATION DATASET\n",
    "# =========================================================\n",
    "\n",
    "panel = pd.read_csv(DATA_FILE)\n",
    "\n",
    "required_cols = [\n",
    "    \"country\", \"year\",\n",
    "    \"EAR\", \"ROA\", \"LLR\", \"LIQ\", \"WFS\",\n",
    "    \"frag_capital\", \"frag_profit\", \"frag_assetq\", \"frag_liquidity\",\n",
    "    \"stress_score\", \"y_true\", \"y_alt\",\n",
    "    \"EAR_lag1\", \"ROA_lag1\", \"LLR_lag1\", \"LIQ_lag1\",\n",
    "    \"prev_y\",\n",
    "]\n",
    "\n",
    "missing_cols = [c for c in required_cols if c not in panel.columns]\n",
    "\n",
    "if missing_cols:\n",
    "    raise ValueError(f\"Missing required columns in {DATA_FILE}: {missing_cols}\")\n",
    "\n",
    "panel[\"year\"] = pd.to_numeric(panel[\"year\"], errors=\"coerce\").astype(int)\n",
    "panel = panel.sort_values([\"country\", \"year\"]).reset_index(drop=True)\n",
    "\n",
    "print(\"Loaded replication dataset:\", DATA_FILE)\n",
    "print(\"Panel shape:\", panel.shape)\n",
    "print(\"Countries:\", sorted(panel[\"country\"].unique()))\n",
    "print(\"Years:\", int(panel[\"year\"].min()), \"-\", int(panel[\"year\"].max()))\n",
    "\n",
    "# =========================================================\n",
    "# 5. BASIC DATA SUMMARY\n",
    "# =========================================================\n",
    "\n",
    "summary_cols = [\"EAR\", \"ROA\", \"LLR\", \"LIQ\", \"WFS\"]\n",
    "\n",
    "print(\"\\nSummary statistics for core indicators:\")\n",
    "print(panel[summary_cols].describe().T[[\"mean\", \"std\", \"min\", \"max\"]])\n",
    "\n",
    "print(\"\\nMissing values in core indicators and lagged predictors:\")\n",
    "print(panel[\n",
    "    [\"EAR\", \"ROA\", \"LLR\", \"LIQ\", \"WFS\",\n",
    "     \"EAR_lag1\", \"ROA_lag1\", \"LLR_lag1\", \"LIQ_lag1\", \"prev_y\"]\n",
    "].isna().sum())\n",
    "# =========================================================\n",
    "# 6. VALIDATE TARGET VARIABLES\n",
    "# =========================================================\n",
    "\n",
    "if TARGET_COL not in [\"y_true\", \"y_alt\"]:\n",
    "    raise ValueError(\"TARGET_COL must be either 'y_true' or 'y_alt'.\")\n",
    "panel[\"prev_target\"] = panel.groupby(\"country\")[TARGET_COL].shift(1)\n",
    "\n",
    "print(\"\\nPrimary target distribution:\")\n",
    "print(panel[\"y_true\"].value_counts(normalize=True).sort_index())\n",
    "\n",
    "print(\"\\nAlternative target distribution:\")\n",
    "print(panel[\"y_alt\"].value_counts(normalize=True).sort_index())\n",
    "\n",
    "print(\"\\nStress score distribution:\")\n",
    "print(panel[\"stress_score\"].value_counts().sort_index())\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 7. BUILD LAGGED FEATURES\n",
    "# =========================================================\n",
    "\n",
    "main_features = [\"EAR\", \"ROA\", \"LLR\", \"LIQ\"]\n",
    "\n",
    "print(\"\\nFeatures used:\", main_features)\n",
    "\n",
    "\n",
    "feature_lags_main = [f\"{c}_lag1\" for c in main_features]\n",
    "\n",
    "# =========================================================\n",
    "#8. CORRELATION MATRIX AND VIF DIAGNOSTICS\n",
    "# =========================================================\n",
    "\n",
    "# Use lagged predictors\n",
    "diag_data = panel[feature_lags_main].copy()\n",
    "\n",
    "# Drop missing values\n",
    "diag_data = diag_data.dropna().reset_index(drop=True)\n",
    "\n",
    "# =========================================================\n",
    "# 1. CORRELATION MATRIX\n",
    "# =========================================================\n",
    "\n",
    "corr_matrix = diag_data.corr()\n",
    "\n",
    "print(\"\\n=== CORRELATION MATRIX ===\")\n",
    "print(corr_matrix.round(3))\n",
    "\n",
    "# Optional: save\n",
    "corr_matrix.to_csv(\n",
    "    os.path.join(OUTPUT_DIR, \"correlation_matrix.csv\")\n",
    ")\n",
    "\n",
    "# =========================================================\n",
    "# 2. VARIANCE INFLATION FACTORS (VIF)\n",
    "# =========================================================\n",
    "\n",
    "X_vif = sm.add_constant(diag_data)\n",
    "\n",
    "vif_table = pd.DataFrame({\n",
    "    \"Variable\": X_vif.columns,\n",
    "    \"VIF\": [\n",
    "        variance_inflation_factor(X_vif.values, i)\n",
    "        for i in range(X_vif.shape[1])\n",
    "    ]\n",
    "})\n",
    "\n",
    "# Remove intercept row\n",
    "vif_table = vif_table[vif_table[\"Variable\"] != \"const\"]\n",
    "\n",
    "print(\"\\n=== VARIANCE INFLATION FACTORS ===\")\n",
    "print(vif_table.round(3).to_string(index=False))\n",
    "\n",
    "# Optional: save\n",
    "vif_table.to_csv(\n",
    "    os.path.join(OUTPUT_DIR, \"vif_diagnostics.csv\"),\n",
    "    index=False\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 9. OOS DATES\n",
    "# =========================================================\n",
    "\n",
    "oos_dates = make_oos_dates(panel, warmup=WARMUP_YEARS)\n",
    "\n",
    "if oos_dates.empty:\n",
    "    raise RuntimeError(\"No country has enough years for out-of-sample evaluation.\")\n",
    "\n",
    "print(\"\\nOOS dates sample:\")\n",
    "print(oos_dates.head())\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 10. STRUCTURAL BASELINE\n",
    "# =========================================================\n",
    "\n",
    "def compute_structural_prob(\n",
    "    df,\n",
    "    country,\n",
    "    year,\n",
    "    target_col=\"y_true\",\n",
    "    alpha=0.5,\n",
    "    k=2.0,\n",
    "    eps=EPS,\n",
    "):\n",
    "    \"\"\"\n",
    "    Structural persistence model:\n",
    "    EWMA of country-specific past distress, shrunk toward pooled historical prevalence.\n",
    "\n",
    "    Uses only observations with year < forecast year.\n",
    "    \"\"\"\n",
    "    hist_all = df[df[\"year\"] < year].copy()\n",
    "\n",
    "    if hist_all.empty:\n",
    "        return 0.5\n",
    "\n",
    "    global_prior = hist_all[target_col].mean()\n",
    "\n",
    "    if pd.isna(global_prior):\n",
    "        global_prior = 0.5\n",
    "\n",
    "    hist_c = hist_all[hist_all[\"country\"] == country].sort_values(\"year\").copy()\n",
    "\n",
    "    if hist_c.empty:\n",
    "        return float(safe_prob(global_prior, eps=eps))\n",
    "\n",
    "    ewma = hist_c[target_col].ewm(alpha=alpha, adjust=False).mean()\n",
    "\n",
    "    n_hist = len(hist_c)\n",
    "    lam = n_hist / (n_hist + k)\n",
    "\n",
    "    m_last = ewma.iloc[-1]\n",
    "\n",
    "    if pd.isna(m_last):\n",
    "        m_last = global_prior\n",
    "\n",
    "    p_struct = lam * m_last + (1.0 - lam) * global_prior\n",
    "\n",
    "    return float(safe_prob(p_struct, eps=eps))\n",
    "\n",
    "\n",
    "def structural_oos(df, oos_dates, target_col=\"y_true\", alpha=0.5, k=2.0):\n",
    "    rows = []\n",
    "\n",
    "    for _, row in oos_dates.iterrows():\n",
    "        c = row[\"country\"]\n",
    "        y_star = int(row[\"year\"])\n",
    "\n",
    "        test_row = df[(df[\"country\"] == c) & (df[\"year\"] == y_star)]\n",
    "\n",
    "        if test_row.empty:\n",
    "            continue\n",
    "\n",
    "        p_struct = compute_structural_prob(\n",
    "            df,\n",
    "            c,\n",
    "            y_star,\n",
    "            target_col=target_col,\n",
    "            alpha=alpha,\n",
    "            k=k,\n",
    "            eps=EPS,\n",
    "        )\n",
    "\n",
    "        rows.append(\n",
    "            {\n",
    "                \"country\": c,\n",
    "                \"year\": y_star,\n",
    "                \"h\": 1,\n",
    "                target_col: int(test_row[target_col].iloc[0]),\n",
    "                \"p_struct\": p_struct,\n",
    "            }\n",
    "        )\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 11. DISCRIMINATIVE LOGIT OOS\n",
    "# =========================================================\n",
    "\n",
    "def logit_oos_recursive_pooled(df, oos_dates, features, target_col=\"y_true\"):\n",
    "    \"\"\"\n",
    "    Pooled recursive ridge logit:\n",
    "    For each forecast year, train on all countries with year < forecast year.\n",
    "    \"\"\"\n",
    "    rows = []\n",
    "\n",
    "    for _, row in oos_dates.iterrows():\n",
    "        c = row[\"country\"]\n",
    "        y_star = int(row[\"year\"])\n",
    "\n",
    "        tr = df[df[\"year\"] < y_star].copy()\n",
    "        te = df[(df[\"country\"] == c) & (df[\"year\"] == y_star)].copy()\n",
    "\n",
    "        if te.empty:\n",
    "            continue\n",
    "\n",
    "        tr_model = tr.dropna(subset=features + [target_col]).copy()\n",
    "        ytr = tr_model[target_col].astype(int)\n",
    "\n",
    "        if len(tr_model) < 8 or ytr.nunique() < 2:\n",
    "            prior = tr[target_col].mean()\n",
    "\n",
    "            if pd.isna(prior):\n",
    "                prior = df[target_col].mean()\n",
    "\n",
    "            if pd.isna(prior):\n",
    "                prior = 0.5\n",
    "\n",
    "            p = float(prior)\n",
    "\n",
    "        else:\n",
    "            pipe = make_logit_pipeline()\n",
    "            pipe.fit(tr_model[features], ytr)\n",
    "            p = float(pipe.predict_proba(te[features])[0, 1])\n",
    "\n",
    "        rows.append(\n",
    "            {\n",
    "                \"country\": c,\n",
    "                \"year\": int(y_star),\n",
    "                \"h\": 1,\n",
    "                \"p_logit\": float(safe_prob(p, eps=EPS)),\n",
    "            }\n",
    "        )\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "def expanding_logit_coefficients(df, oos_dates, features, target_col=\"y_true\"):\n",
    "    \"\"\"\n",
    "    Coefficient paths using the same pipeline as the predictive logit.\n",
    "    Coefficients are standardized-scale coefficients.\n",
    "    \"\"\"\n",
    "    coef_rows = []\n",
    "\n",
    "    for _, row in oos_dates.iterrows():\n",
    "        y_star = int(row[\"year\"])\n",
    "\n",
    "        tr = df[df[\"year\"] < y_star].copy()\n",
    "        tr_model = tr.dropna(subset=features + [target_col]).copy()\n",
    "\n",
    "        if len(tr_model) < 8:\n",
    "            continue\n",
    "\n",
    "        ytr = tr_model[target_col].astype(int)\n",
    "\n",
    "        if ytr.nunique() < 2:\n",
    "            continue\n",
    "\n",
    "        pipe = make_logit_pipeline()\n",
    "        pipe.fit(tr_model[features], ytr)\n",
    "\n",
    "        coefs = pipe.named_steps[\"logisticregression\"].coef_[0]\n",
    "\n",
    "        coef_rows.append(\n",
    "            {\"forecast_year\": y_star, **dict(zip(features, coefs))}\n",
    "        )\n",
    "\n",
    "    return pd.DataFrame(coef_rows)\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 12. BUILD OOS TABLE\n",
    "# =========================================================\n",
    "\n",
    "oos_struct = structural_oos(\n",
    "    panel,\n",
    "    oos_dates,\n",
    "    target_col=TARGET_COL,\n",
    "    alpha=STRUCT_ALPHA,\n",
    "    k=STRUCT_K,\n",
    ")\n",
    "\n",
    "oos_logit = logit_oos_recursive_pooled(\n",
    "    panel,\n",
    "    oos_dates,\n",
    "    feature_lags_main,\n",
    "    target_col=TARGET_COL,\n",
    ")\n",
    "\n",
    "oos = (\n",
    "    oos_struct.merge(oos_logit, on=[\"country\", \"year\", \"h\"], how=\"left\")\n",
    "    .sort_values([\"country\", \"year\"])\n",
    "    .reset_index(drop=True)\n",
    ")\n",
    "\n",
    "oos = oos.merge(\n",
    "    panel[[\"country\", \"year\", \"prev_target\"]],\n",
    "    on=[\"country\", \"year\"],\n",
    "    how=\"left\",\n",
    ")\n",
    "\n",
    "oos[\"p_naive\"] = [\n",
    "    compute_naive_prob(panel, c, y, target_col=TARGET_COL)\n",
    "    for c, y in zip(oos[\"country\"], oos[\"year\"])\n",
    "]\n",
    "\n",
    "oos[\"p_lag\"] = [\n",
    "    compute_lag_prob(panel, c, y, target_col=TARGET_COL)\n",
    "    for c, y in zip(oos[\"country\"], oos[\"year\"])\n",
    "]\n",
    "\n",
    "# Standardize target column name for downstream plotting if needed.\n",
    "if TARGET_COL != \"y_true\":\n",
    "    oos[\"y_true\"] = oos[TARGET_COL]\n",
    "\n",
    "print(\"\\nCheck benchmark equality:\")\n",
    "print(\"NAIVE equals LAG?\", np.allclose(oos[\"p_naive\"], oos[\"p_lag\"], equal_nan=True))\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 13. HYBRID FITTING\n",
    "# =========================================================\n",
    "\n",
    "def fit_offset_glm(lp_struct, lp_logit, y, alpha=1e-4):\n",
    "    \"\"\"\n",
    "    Estimate hybrid logit:\n",
    "    logit(p_H) = a + (1-w)logit(p_S) + w logit(p_D)\n",
    "\n",
    "    Equivalent offset form:\n",
    "    logit(p_H) = offset(logit(p_S)) + a + w[logit(p_D)-logit(p_S)]\n",
    "\n",
    "    w is clipped to [0,1] to match the manuscript.\n",
    "    \"\"\"\n",
    "    X = pd.DataFrame({\"delta\": lp_logit - lp_struct})\n",
    "    X = sm.add_constant(X, has_constant=\"add\")\n",
    "\n",
    "    glm = sm.GLM(\n",
    "        y.astype(int),\n",
    "        X,\n",
    "        family=sm.families.Binomial(),\n",
    "        offset=lp_struct,\n",
    "    )\n",
    "\n",
    "    try:\n",
    "        res = glm.fit_regularized(alpha=alpha, L1_wt=0.0)\n",
    "        a = float(res.params[\"const\"])\n",
    "        w = float(res.params[\"delta\"])\n",
    "    except Exception:\n",
    "        res = glm.fit()\n",
    "        a = float(res.params[\"const\"])\n",
    "        w = float(res.params[\"delta\"])\n",
    "\n",
    "    return float(np.clip(w, 0.0, 1.0)), float(a)\n",
    "\n",
    "\n",
    "def cross_fitted_hybrid(\n",
    "    oos_df,\n",
    "    target_col=\"y_true\",\n",
    "    use_isotonic=True,\n",
    "    iso_blend=0.10,\n",
    "    eps=EPS,\n",
    "):\n",
    "    \"\"\"\n",
    "    Leave-one-country-out hybrid fitting on OOS predictions.\n",
    "    Calibration is supplementary and reported separately.\n",
    "    \"\"\"\n",
    "    df = oos_df.dropna(subset=[target_col, \"p_struct\", \"p_logit\", \"country\"]).copy()\n",
    "\n",
    "    df[\"p_struct\"] = safe_prob(df[\"p_struct\"].values, eps=eps)\n",
    "    df[\"p_logit\"] = safe_prob(df[\"p_logit\"].values, eps=eps)\n",
    "\n",
    "    if len(df) < 8 or df[target_col].nunique() < 2:\n",
    "        df[\"p_hybrid_cv\"] = 0.5 * df[\"p_struct\"] + 0.5 * df[\"p_logit\"]\n",
    "        df[\"p_hybrid_cv_cal\"] = df[\"p_hybrid_cv\"]\n",
    "\n",
    "        return {\"mode\": \"avg_too_small\", \"a\": 0.0, \"w\": 0.5}, df\n",
    "\n",
    "    y = df[target_col].astype(int).values\n",
    "    lp_struct = safe_logit(df[\"p_struct\"].values, eps)\n",
    "    lp_logit = safe_logit(df[\"p_logit\"].values, eps)\n",
    "\n",
    "    df[\"p_hybrid_cv\"] = np.nan\n",
    "\n",
    "    for c in df[\"country\"].unique():\n",
    "        te = df[\"country\"].values == c\n",
    "        tr = ~te\n",
    "\n",
    "        if tr.sum() < 6 or np.unique(y[tr]).size < 2:\n",
    "            p_te = np.clip(\n",
    "                0.5 * df.loc[te, \"p_struct\"].values\n",
    "                + 0.5 * df.loc[te, \"p_logit\"].values,\n",
    "                eps,\n",
    "                1.0 - eps,\n",
    "            )\n",
    "            df.loc[te, \"p_hybrid_cv\"] = p_te\n",
    "            continue\n",
    "\n",
    "        w, a = fit_offset_glm(lp_struct[tr], lp_logit[tr], y[tr], alpha=1e-4)\n",
    "\n",
    "        z_te = a + w * (lp_logit[te] - lp_struct[te]) + lp_struct[te]\n",
    "        p_te = sigmoid(z_te)\n",
    "\n",
    "        df.loc[te, \"p_hybrid_cv\"] = safe_prob(p_te, eps=eps)\n",
    "\n",
    "    if use_isotonic and df[\"p_hybrid_cv\"].nunique() > 2 and df[target_col].nunique() > 1:\n",
    "        df[\"p_hybrid_cv_cal\"] = np.nan\n",
    "\n",
    "        for c in df[\"country\"].unique():\n",
    "            te = df[\"country\"].values == c\n",
    "            tr = ~te\n",
    "\n",
    "            if (\n",
    "                tr.sum() < 8\n",
    "                or np.unique(y[tr]).size < 2\n",
    "                or df.loc[tr, \"p_hybrid_cv\"].nunique() < 3\n",
    "            ):\n",
    "                df.loc[te, \"p_hybrid_cv_cal\"] = df.loc[te, \"p_hybrid_cv\"].values\n",
    "                continue\n",
    "\n",
    "            iso = IsotonicRegression(out_of_bounds=\"clip\")\n",
    "            iso.fit(df.loc[tr, \"p_hybrid_cv\"].values, df.loc[tr, target_col].values)\n",
    "\n",
    "            p_iso = iso.transform(df.loc[te, \"p_hybrid_cv\"].values)\n",
    "\n",
    "            df.loc[te, \"p_hybrid_cv_cal\"] = np.clip(\n",
    "                (1.0 - iso_blend) * p_iso\n",
    "                + iso_blend * df.loc[te, \"p_hybrid_cv\"].values,\n",
    "                eps,\n",
    "                1.0 - eps,\n",
    "            )\n",
    "    else:\n",
    "        df[\"p_hybrid_cv_cal\"] = df[\"p_hybrid_cv\"]\n",
    "\n",
    "    w_all, a_all = fit_offset_glm(lp_struct, lp_logit, y, alpha=1e-4)\n",
    "\n",
    "    return {\"mode\": \"offset_glm_cv\", \"a\": a_all, \"w\": w_all}, df\n",
    "\n",
    "\n",
    "fit_stack, oos_preds = cross_fitted_hybrid(\n",
    "    oos,\n",
    "    target_col=TARGET_COL,\n",
    "    use_isotonic=USE_ISOTONIC,\n",
    "    iso_blend=ISO_BLEND,\n",
    ")\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 14. RESULTS\n",
    "# =========================================================\n",
    "\n",
    "results_table = compare_models(\n",
    "    oos_preds,\n",
    "    target_col=TARGET_COL,\n",
    "    include_calibrated=False,\n",
    ")\n",
    "\n",
    "results_table_with_cal = compare_models(\n",
    "    oos_preds,\n",
    "    target_col=TARGET_COL,\n",
    "    include_calibrated=True,\n",
    ")\n",
    "\n",
    "print(\"\\n=== MAIN MODEL COMPARISON ===\")\n",
    "print(results_table.to_string(index=False))\n",
    "\n",
    "print(\"\\n=== SUPPLEMENTARY MODEL COMPARISON WITH CALIBRATED HYBRID ===\")\n",
    "print(results_table_with_cal.to_string(index=False))\n",
    "\n",
    "print(\"\\n=== HYBRID PARAMETERS - FULL OOS FIT FOR REPORTING ===\")\n",
    "print(fit_stack)\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 15. BOOTSTRAP AUC COMPARISONS\n",
    "# =========================================================\n",
    "\n",
    "print(\"\\n=== POOLED BOOTSTRAP AUC COMPARISONS ===\")\n",
    "\n",
    "y = oos_preds[TARGET_COL].values.astype(int)\n",
    "\n",
    "comparisons = [\n",
    "    (\"p_struct\", \"p_logit\", \"STRUCT vs LOGIT\"),\n",
    "    (\"p_struct\", \"p_hybrid_cv\", \"STRUCT vs HYBRID\"),\n",
    "    (\"p_logit\", \"p_hybrid_cv\", \"LOGIT vs HYBRID\"),\n",
    "    (\"p_naive\", \"p_lag\", \"NAIVE vs LAG\"),\n",
    "]\n",
    "\n",
    "boot_rows = []\n",
    "\n",
    "for c1, c2, label in comparisons:\n",
    "    mask = oos_preds[[c1, c2, TARGET_COL]].notna().all(axis=1).values\n",
    "\n",
    "    if mask.sum() < 3 or len(np.unique(y[mask])) < 2:\n",
    "        print(label, \"Not enough valid observations/classes.\")\n",
    "        continue\n",
    "\n",
    "    res = bootstrap_auc_diff(\n",
    "        y[mask],\n",
    "        oos_preds.loc[mask, c1].values.astype(float),\n",
    "        oos_preds.loc[mask, c2].values.astype(float),\n",
    "        n_boot=1000,\n",
    "        random_state=RANDOM_STATE,\n",
    "    )\n",
    "\n",
    "    boot_rows.append(\n",
    "        {\n",
    "            \"Comparison\": label,\n",
    "            \"Mean Diff.\": res[\"mean_diff\"],\n",
    "            \"Lower CI\": res[\"ci_lower\"],\n",
    "            \"Upper CI\": res[\"ci_upper\"],\n",
    "            \"n_boot_used\": res[\"n_boot_used\"],\n",
    "        }\n",
    "    )\n",
    "\n",
    "    print(label, res)\n",
    "\n",
    "bootstrap_table = pd.DataFrame(boot_rows)\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 16. COEFFICIENT PATHS\n",
    "# =========================================================\n",
    "\n",
    "coef_df = expanding_logit_coefficients(\n",
    "    panel,\n",
    "    oos_dates,\n",
    "    feature_lags_main,\n",
    "    target_col=TARGET_COL,\n",
    ")\n",
    "\n",
    "if not coef_df.empty:\n",
    "    coef_summary = (\n",
    "        coef_df[feature_lags_main]\n",
    "        .agg([\"mean\", \"std\"])\n",
    "        .T\n",
    "        .reset_index()\n",
    "        .rename(columns={\"index\": \"Variable\", \"mean\": \"Mean\", \"std\": \"Std. Dev.\"})\n",
    "    )\n",
    "\n",
    "    coef_summary[\"Sign\"] = np.where(coef_summary[\"Mean\"] >= 0, \"+\", \"-\")\n",
    "else:\n",
    "    coef_summary = pd.DataFrame(columns=[\"Variable\", \"Mean\", \"Std. Dev.\", \"Sign\"])\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 17. ROBUSTNESS CHECK: BINNING + WEIGHT OF EVIDENCE (WoE) LOGIT\n",
    "# =========================================================\n",
    "\n",
    "def make_quantile_bins(x, n_bins=4):\n",
    "    \"\"\"\n",
    "    Quantile binning with duplicate-edge handling.\n",
    "    \"\"\"\n",
    "    return pd.qcut(x, q=n_bins, duplicates=\"drop\")\n",
    "\n",
    "def compute_woe_map(x_binned, y, eps=0.5):\n",
    "    \"\"\"\n",
    "    Computes WoE per bin.\n",
    "    WoE = log( non-distress share / distress share )\n",
    "    \"\"\"\n",
    "    tmp = pd.DataFrame({\"bin\": x_binned, \"y\": y}).dropna()\n",
    "\n",
    "    total_good = (tmp[\"y\"] == 0).sum()\n",
    "    total_bad = (tmp[\"y\"] == 1).sum()\n",
    "\n",
    "    woe_map = {}\n",
    "\n",
    "    for b, g in tmp.groupby(\"bin\", observed=False):\n",
    "        good = (g[\"y\"] == 0).sum()\n",
    "        bad = (g[\"y\"] == 1).sum()\n",
    "\n",
    "        good_share = (good + eps) / (total_good + eps)\n",
    "        bad_share = (bad + eps) / (total_bad + eps)\n",
    "\n",
    "        woe_map[b] = np.log(good_share / bad_share)\n",
    "\n",
    "    return woe_map\n",
    "\n",
    "def apply_woe(train_x, train_y, test_x, n_bins=4):\n",
    "    \"\"\"\n",
    "    Fits bins and WoE on training data only, then applies to test data.\n",
    "    \"\"\"\n",
    "    train_bins = make_quantile_bins(train_x, n_bins=n_bins)\n",
    "\n",
    "    # extract bin edges from training qcut\n",
    "    categories = train_bins.cat.categories\n",
    "\n",
    "    if len(categories) < 2:\n",
    "        return (\n",
    "            pd.Series(np.zeros(len(train_x)), index=train_x.index),\n",
    "            pd.Series(np.zeros(len(test_x)), index=test_x.index),\n",
    "        )\n",
    "\n",
    "    edges = [categories[0].left] + [c.right for c in categories]\n",
    "    edges[0] = -np.inf\n",
    "    edges[-1] = np.inf\n",
    "\n",
    "    train_bins = pd.cut(train_x, bins=edges, include_lowest=True)\n",
    "    test_bins = pd.cut(test_x, bins=edges, include_lowest=True)\n",
    "\n",
    "    woe_map = compute_woe_map(train_bins, train_y)\n",
    "\n",
    "    train_woe = train_bins.map(woe_map).astype(float)\n",
    "    test_woe = test_bins.map(woe_map).astype(float)\n",
    "\n",
    "    train_woe = train_woe.fillna(0.0)\n",
    "    test_woe = test_woe.fillna(0.0)\n",
    "\n",
    "    return train_woe, test_woe\n",
    "\n",
    "def recursive_woe_logit_oos(df, oos_dates, features, target_col=\"y_true\", n_bins=4):\n",
    "    rows = []\n",
    "    coef_rows = []\n",
    "\n",
    "    for _, row in oos_dates.iterrows():\n",
    "        c = row[\"country\"]\n",
    "        y_star = int(row[\"year\"])\n",
    "\n",
    "        tr = df[df[\"year\"] < y_star].copy()\n",
    "        te = df[(df[\"country\"] == c) & (df[\"year\"] == y_star)].copy()\n",
    "\n",
    "        if te.empty:\n",
    "            continue\n",
    "\n",
    "        tr_model = tr.dropna(subset=features + [target_col]).copy()\n",
    "        te_model = te.copy()\n",
    "\n",
    "        ytr = tr_model[target_col].astype(int)\n",
    "\n",
    "        if len(tr_model) < 8 or ytr.nunique() < 2:\n",
    "            prior = tr[target_col].mean()\n",
    "            if pd.isna(prior):\n",
    "                prior = df[target_col].mean()\n",
    "            if pd.isna(prior):\n",
    "                prior = 0.5\n",
    "\n",
    "            rows.append({\n",
    "                \"country\": c,\n",
    "                \"year\": y_star,\n",
    "                \"h\": 1,\n",
    "                target_col: int(te[target_col].iloc[0]),\n",
    "                \"p_logit_woe\": float(np.clip(prior, 1e-6, 1 - 1e-6)),\n",
    "            })\n",
    "            continue\n",
    "\n",
    "        Xtr_woe = pd.DataFrame(index=tr_model.index)\n",
    "        Xte_woe = pd.DataFrame(index=te_model.index)\n",
    "\n",
    "        for f in features:\n",
    "            train_woe, test_woe = apply_woe(\n",
    "                tr_model[f],\n",
    "                ytr,\n",
    "                te_model[f],\n",
    "                n_bins=n_bins\n",
    "            )\n",
    "\n",
    "            Xtr_woe[f\"{f}_woe\"] = train_woe\n",
    "            Xte_woe[f\"{f}_woe\"] = test_woe\n",
    "\n",
    "        model = make_pipeline(\n",
    "            SimpleImputer(strategy=\"median\"),\n",
    "            StandardScaler(),\n",
    "            LogisticRegression(\n",
    "                penalty=\"l2\",\n",
    "                solver=\"lbfgs\",\n",
    "                max_iter=1000,\n",
    "                random_state=RANDOM_STATE\n",
    "            )\n",
    "        )\n",
    "\n",
    "        model.fit(Xtr_woe, ytr)\n",
    "        p = model.predict_proba(Xte_woe)[0, 1]\n",
    "\n",
    "        rows.append({\n",
    "            \"country\": c,\n",
    "            \"year\": y_star,\n",
    "            \"h\": 1,\n",
    "            target_col: int(te[target_col].iloc[0]),\n",
    "            \"p_logit_woe\": float(np.clip(p, 1e-6, 1 - 1e-6)),\n",
    "        })\n",
    "\n",
    "        coefs = model.named_steps[\"logisticregression\"].coef_[0]\n",
    "        coef_rows.append({\n",
    "            \"forecast_year\": y_star,\n",
    "            **dict(zip(Xtr_woe.columns, coefs))\n",
    "        })\n",
    "\n",
    "    return pd.DataFrame(rows), pd.DataFrame(coef_rows)\n",
    "\n",
    "# Run WoE recursive OOS logit\n",
    "oos_woe, coef_woe = recursive_woe_logit_oos(\n",
    "    panel,\n",
    "    oos_dates,\n",
    "    feature_lags_main,\n",
    "    target_col=TARGET_COL,\n",
    "    n_bins=4\n",
    ")\n",
    "\n",
    "# Merge with your existing OOS predictions\n",
    "oos_compare = oos_preds.merge(\n",
    "    oos_woe[[\"country\", \"year\", \"p_logit_woe\"]],\n",
    "    on=[\"country\", \"year\"],\n",
    "    how=\"left\"\n",
    ")\n",
    "\n",
    "def evaluate_single_model(df, y_col, p_col, label):\n",
    "    tmp = df[[y_col, p_col]].dropna().copy()\n",
    "    y = tmp[y_col].astype(int).values\n",
    "    p = np.clip(tmp[p_col].astype(float).values, 1e-6, 1 - 1e-6)\n",
    "\n",
    "    return {\n",
    "        \"Model\": label,\n",
    "        \"Brier\": brier_score_loss(y, p),\n",
    "        \"LogLoss\": log_loss(y, p, labels=[0, 1]),\n",
    "        \"AUC\": roc_auc_score(y, p) if len(np.unique(y)) > 1 else np.nan,\n",
    "        \"AP\": average_precision_score(y, p) if len(np.unique(y)) > 1 else np.nan,\n",
    "        \"N\": len(y)\n",
    "    }\n",
    "\n",
    "robustness_results = pd.DataFrame([\n",
    "    evaluate_single_model(oos_compare, TARGET_COL, \"p_logit\", \"Raw continuous logit\"),\n",
    "    evaluate_single_model(oos_compare, TARGET_COL, \"p_logit_woe\", \"WoE-binned logit\"),\n",
    "    evaluate_single_model(oos_compare, TARGET_COL, \"p_struct\", \"Structural baseline\"),\n",
    "    evaluate_single_model(oos_compare, TARGET_COL, \"p_hybrid_cv\", \"Hybrid\")\n",
    "])\n",
    "\n",
    "print(\"\\n=== WoE ROBUSTNESS RESULTS ===\")\n",
    "print(robustness_results.to_string(index=False))\n",
    "\n",
    "print(\"\\n=== WoE COEFFICIENT SUMMARY ===\")\n",
    "if not coef_woe.empty:\n",
    "    coef_woe_summary = (\n",
    "        coef_woe.drop(columns=[\"forecast_year\"])\n",
    "        .agg([\"mean\", \"std\"])\n",
    "        .T\n",
    "        .reset_index()\n",
    "        .rename(columns={\"index\": \"Variable\", \"mean\": \"Mean\", \"std\": \"Std. Dev.\"})\n",
    "    )\n",
    "    coef_woe_summary[\"Sign\"] = np.where(coef_woe_summary[\"Mean\"] >= 0, \"+\", \"-\")\n",
    "    print(coef_woe_summary.to_string(index=False))\n",
    "else:\n",
    "    print(\"No WoE coefficients estimated.\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 18. SAVE TABLE OUTPUTS\n",
    "# =========================================================\n",
    "\n",
    "oos_preds.to_csv(os.path.join(OUTPUT_DIR, \"oos_predictions_hybrid.csv\"), index=False)\n",
    "results_table.to_csv(os.path.join(OUTPUT_DIR, \"results_table_main.csv\"), index=False)\n",
    "results_table_with_cal.to_csv(os.path.join(OUTPUT_DIR, \"results_table_with_calibration.csv\"), index=False)\n",
    "bootstrap_table.to_csv(os.path.join(OUTPUT_DIR, \"bootstrap_auc_comparisons.csv\"), index=False)\n",
    "coef_df.to_csv(os.path.join(OUTPUT_DIR, \"recursive_logit_coefficients.csv\"), index=False)\n",
    "coef_summary.to_csv(os.path.join(OUTPUT_DIR, \"logit_coefficient_summary.csv\"), index=False)\n",
    "oos_compare.to_csv(os.path.join(OUTPUT_DIR, \"oos_predictions_with_woe_logit.csv\"), index=False)\n",
    "robustness_results.to_csv(os.path.join(OUTPUT_DIR, \"woe_robustness_results.csv\"), index=False)\n",
    "coef_woe.to_csv(os.path.join(OUTPUT_DIR, \"woe_recursive_logit_coefficients.csv\"), index=False)\n",
    "\n",
    "if not coef_woe.empty:\n",
    "    coef_woe_summary.to_csv(os.path.join(OUTPUT_DIR, \"woe_coefficient_summary.csv\"), index=False)\n",
    "\n",
    "print(\"\\nSaved table outputs to:\", OUTPUT_DIR)\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# 19. PLOTS\n",
    "# =========================================================\n",
    "\n",
    "plot_target = TARGET_COL\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(5.5, 5))\n",
    "\n",
    "roc_models = {\n",
    "    \"Structural baseline (EWMA)\": \"p_struct\",\n",
    "    \"Discriminative logit\": \"p_logit\",\n",
    "    \"Hybrid\": \"p_hybrid_cv\",\n",
    "    \"Naive prevalence\": \"p_naive\",\n",
    "    \"Lag only\": \"p_lag\",\n",
    "}\n",
    "\n",
    "for label, col in roc_models.items():\n",
    "    y_plot, p_plot = valid_xy(oos_preds, plot_target, col)\n",
    "\n",
    "    if len(y_plot) == 0 or len(np.unique(y_plot)) < 2:\n",
    "        continue\n",
    "\n",
    "    fpr, tpr, _ = roc_curve(y_plot, p_plot)\n",
    "    ax.plot(\n",
    "        fpr,\n",
    "        tpr,\n",
    "        linewidth=1.8,\n",
    "        label=f\"{label} (AUC = {auc(fpr, tpr):.3f})\",\n",
    "    )\n",
    "\n",
    "ax.plot([0, 1], [0, 1], \"k--\", linewidth=1)\n",
    "ax.set_title(\"ROC curves (pooled out-of-sample)\", fontsize=10)\n",
    "ax.set_xlabel(\"False positive rate\")\n",
    "ax.set_ylabel(\"True positive rate\")\n",
    "ax.legend(loc=\"lower right\", fontsize=7)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(FIG_DIR, \"roc_curves.png\"), dpi=300, bbox_inches=\"tight\")\n",
    "plt.close(fig)\n",
    "\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(5.5, 5))\n",
    "\n",
    "pr_models = {\n",
    "    \"Structural baseline (EWMA)\": \"p_struct\",\n",
    "    \"Discriminative logit\": \"p_logit\",\n",
    "    \"Hybrid\": \"p_hybrid_cv\",\n",
    "    \"Naive prevalence\": \"p_naive\",\n",
    "    \"Lag only\": \"p_lag\",\n",
    "}\n",
    "\n",
    "for label, col in pr_models.items():\n",
    "    y_plot, p_plot = valid_xy(oos_preds, plot_target, col)\n",
    "\n",
    "    if len(y_plot) == 0 or len(np.unique(y_plot)) < 2:\n",
    "        continue\n",
    "\n",
    "    precision, recall, _ = precision_recall_curve(y_plot, p_plot)\n",
    "    ap = average_precision_score(y_plot, p_plot)\n",
    "\n",
    "    ax.plot(\n",
    "        recall,\n",
    "        precision,\n",
    "        linewidth=1.8,\n",
    "        label=f\"{label} (AP = {ap:.3f})\",\n",
    "    )\n",
    "\n",
    "baseline = oos_preds[plot_target].mean()\n",
    "\n",
    "ax.hlines(\n",
    "    baseline,\n",
    "    0,\n",
    "    1,\n",
    "    linestyles=\"--\",\n",
    "    linewidth=1,\n",
    "    label=f\"Baseline = {baseline:.3f}\",\n",
    ")\n",
    "\n",
    "ax.set_title(\"Precision-recall curves\", fontsize=10)\n",
    "ax.set_xlabel(\"Recall\")\n",
    "ax.set_ylabel(\"Precision\")\n",
    "ax.legend(fontsize=7)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(FIG_DIR, \"precision_recall_curves.png\"), dpi=300, bbox_inches=\"tight\")\n",
    "plt.close(fig)\n",
    "\n",
    "# =========================================================\n",
    "# PROBABILITY DISTRIBUTION PLOT \n",
    "# =========================================================\n",
    "\n",
    "dist_models = {\n",
    "    \"Structural\": \"p_struct\",\n",
    "    \"Hybrid\": \"p_hybrid_cv\",\n",
    "    \"Logit\": \"p_logit\",\n",
    "}\n",
    "\n",
    "fig, axes = plt.subplots(\n",
    "    1,\n",
    "    3,\n",
    "    figsize=(12, 4),\n",
    "    sharey=True\n",
    ")\n",
    "\n",
    "for ax, (label, col) in zip(axes, dist_models.items()):\n",
    "\n",
    "    tmp = oos_preds[[TARGET_COL, col]].dropna().copy()\n",
    "\n",
    "    if tmp.empty:\n",
    "        continue\n",
    "\n",
    "    no_distress = tmp[tmp[TARGET_COL] == 0]\n",
    "\n",
    "    if not no_distress.empty:\n",
    "        sns.kdeplot(\n",
    "            data=no_distress,\n",
    "            x=col,\n",
    "            fill=True,\n",
    "            alpha=0.4,\n",
    "            label=\"No distress\",\n",
    "            ax=ax,\n",
    "            cut=0,\n",
    "            clip=(0, 1),\n",
    "            linewidth=1.5\n",
    "        )\n",
    "\n",
    "    distress = tmp[tmp[TARGET_COL] == 1]\n",
    "\n",
    "    if not distress.empty:\n",
    "        sns.kdeplot(\n",
    "            data=distress,\n",
    "            x=col,\n",
    "            fill=True,\n",
    "            alpha=0.4,\n",
    "            label=\"Distress\",\n",
    "            ax=ax,\n",
    "            cut=0,\n",
    "            clip=(0, 1),\n",
    "            linewidth=1.5\n",
    "        )\n",
    "\n",
    "    ax.set_title(label, fontsize=11)\n",
    "    ax.set_xlabel(\"Predicted probability\", fontsize=10)\n",
    "    ax.set_xlim(0, 1)\n",
    "    ax.grid(alpha=0.3)\n",
    "    ax.legend(fontsize=8)\n",
    "\n",
    "axes[0].set_ylabel(\"Density\", fontsize=10)\n",
    "\n",
    "fig.suptitle(\n",
    "    \"Predicted Probability Distributions by Realized Distress Outcomes\",\n",
    "    fontsize=12\n",
    ")\n",
    "\n",
    "plt.tight_layout()\n",
    "\n",
    "dist_path = os.path.join(\n",
    "    FIG_DIR,\n",
    "    \"probability_distributions.png\"\n",
    ")\n",
    "\n",
    "plt.savefig(\n",
    "    dist_path,\n",
    "    dpi=300,\n",
    "    bbox_inches=\"tight\"\n",
    ")\n",
    "\n",
    "plt.close(fig)\n",
    "\n",
    "print(f\"Probability distribution figure saved to: {dist_path}\")\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# APPENDIX: CALIBRATION CURVE \n",
    "# =========================================================\n",
    "\n",
    "cal_models = {\n",
    "    \"Structural\": \"p_struct\",\n",
    "    \"Hybrid\": \"p_hybrid_cv\",\n",
    "}\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(6, 5))\n",
    "\n",
    "for label, col in cal_models.items():\n",
    "\n",
    "    tmp = oos_preds[[TARGET_COL, col]].dropna().copy()\n",
    "\n",
    "    if tmp.empty:\n",
    "        continue\n",
    "\n",
    "    y_true = tmp[TARGET_COL].astype(int).values\n",
    "    probs = tmp[col].astype(float).values\n",
    "\n",
    "    if len(np.unique(y_true)) < 2:\n",
    "        continue\n",
    "\n",
    "    prob_true, prob_pred = calibration_curve(\n",
    "        y_true,\n",
    "        probs,\n",
    "        n_bins=5,\n",
    "        strategy=\"quantile\"\n",
    "    )\n",
    "\n",
    "    ax.plot(\n",
    "        prob_pred,\n",
    "        prob_true,\n",
    "        marker=\"o\",\n",
    "        linewidth=2,\n",
    "        label=label\n",
    "    )\n",
    "\n",
    "ax.plot(\n",
    "    [0, 1],\n",
    "    [0, 1],\n",
    "    linestyle=\"--\",\n",
    "    linewidth=1.5,\n",
    "    label=\"Perfect calibration\"\n",
    ")\n",
    "\n",
    "ax.set_xlabel(\"Mean predicted probability\")\n",
    "ax.set_ylabel(\"Observed distress frequency\")\n",
    "ax.set_title(\"Calibration Curve: Predicted and Observed Distress Probabilities\")\n",
    "ax.legend(fontsize=8)\n",
    "ax.grid(alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "\n",
    "cal_path = os.path.join(\n",
    "    FIG_DIR,\n",
    "    \"appendix_calibration_curve.png\"\n",
    ")\n",
    "\n",
    "plt.savefig(\n",
    "    cal_path,\n",
    "    dpi=300,\n",
    "    bbox_inches=\"tight\"\n",
    ")\n",
    "\n",
    "plt.close(fig)\n",
    "\n",
    "print(f\"Calibration curve saved to: {cal_path}\")\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# RECURSIVE COEFFICIENT PATHS (APPENDIX)\n",
    "# =========================================================\n",
    "\n",
    "if not coef_df.empty:\n",
    "\n",
    "    fig, axes = plt.subplots(\n",
    "        2,\n",
    "        2,\n",
    "        figsize=(10, 7),\n",
    "        sharex=True\n",
    "    )\n",
    "\n",
    "    axes = axes.flatten()\n",
    "\n",
    "    feature_labels = {\n",
    "        \"EAR_lag1\": r\"EAR$_{t-1}$\",\n",
    "        \"ROA_lag1\": r\"ROA$_{t-1}$\",\n",
    "        \"LLR_lag1\": r\"LLR$_{t-1}$\",\n",
    "        \"LIQ_lag1\": r\"LIQ$_{t-1}$\",\n",
    "    }\n",
    "\n",
    "    feature_colors = {\n",
    "        \"EAR_lag1\": \"tab:blue\",\n",
    "        \"ROA_lag1\": \"tab:orange\",\n",
    "        \"LLR_lag1\": \"tab:green\",\n",
    "        \"LIQ_lag1\": \"tab:red\",\n",
    "    }\n",
    "\n",
    "    for ax, col in zip(axes, feature_lags_main):\n",
    "\n",
    "        if col not in coef_df.columns:\n",
    "            ax.set_visible(False)\n",
    "            continue\n",
    "\n",
    "        ax.plot(\n",
    "            coef_df[\"forecast_year\"],\n",
    "            coef_df[col],\n",
    "            marker=\"o\",\n",
    "            linewidth=2,\n",
    "            color=feature_colors.get(col, \"tab:blue\"),\n",
    "        )\n",
    "\n",
    "        ax.axhline(\n",
    "            0,\n",
    "            linestyle=\"--\",\n",
    "            linewidth=1,\n",
    "            color=\"black\",\n",
    "        )\n",
    "\n",
    "        ax.set_title(\n",
    "            f\"{feature_labels.get(col, col)} coefficient path\",\n",
    "            fontsize=10,\n",
    "        )\n",
    "\n",
    "        ax.set_xlabel(\"Forecast year\")\n",
    "        ax.set_ylabel(\"Coefficient\")\n",
    "        ax.grid(alpha=0.3)\n",
    "\n",
    "    fig.suptitle(\n",
    "        \"Recursive Coefficient Paths for Discriminative Model\",\n",
    "        fontsize=12,\n",
    "    )\n",
    "\n",
    "    plt.tight_layout()\n",
    "\n",
    "    coef_path = os.path.join(\n",
    "        FIG_DIR,\n",
    "        \"appendix_coefficient_paths.png\"\n",
    "    )\n",
    "\n",
    "    plt.savefig(\n",
    "        coef_path,\n",
    "        dpi=300,\n",
    "        bbox_inches=\"tight\",\n",
    "    )\n",
    "\n",
    "    plt.close(fig)\n",
    "\n",
    "    print(f\"Coefficient paths figure saved to: {coef_path}\")\n",
    "\n",
    "else:\n",
    "    print(\"Coefficient dataframe is empty.\")\n",
    "\n",
    "# =========================================================\n",
    "# COUNTRY-LEVEL PROBABILITY TRAJECTORIES\n",
    "# =========================================================\n",
    "\n",
    "countries = sorted(oos_preds[\"country\"].dropna().unique())\n",
    "\n",
    "n_cols = 2\n",
    "n_rows = int(np.ceil(len(countries) / n_cols))\n",
    "\n",
    "fig, axes = plt.subplots(\n",
    "    n_rows,\n",
    "    n_cols,\n",
    "    figsize=(10, 3.2 * n_rows),\n",
    "    sharex=False,\n",
    "    sharey=True\n",
    ")\n",
    "\n",
    "axes = axes.flatten()\n",
    "\n",
    "for ax, country in zip(axes, countries):\n",
    "\n",
    "    tmp = (\n",
    "        oos_preds[oos_preds[\"country\"] == country]\n",
    "        .sort_values(\"year\")\n",
    "        .copy()\n",
    "    )\n",
    "\n",
    "    # Ensure integer years\n",
    "    tmp[\"year\"] = tmp[\"year\"].astype(int)\n",
    "\n",
    "    ax.plot(\n",
    "        tmp[\"year\"],\n",
    "        tmp[\"p_struct\"],\n",
    "        marker=\"o\",\n",
    "        linewidth=1.8,\n",
    "        label=\"Structural\"\n",
    "    )\n",
    "\n",
    "    ax.plot(\n",
    "        tmp[\"year\"],\n",
    "        tmp[\"p_hybrid_cv\"],\n",
    "        marker=\"o\",\n",
    "        linewidth=1.8,\n",
    "        label=\"Hybrid\"\n",
    "    )\n",
    "\n",
    "    ax.plot(\n",
    "        tmp[\"year\"],\n",
    "        tmp[\"p_logit\"],\n",
    "        marker=\"o\",\n",
    "        linewidth=1.8,\n",
    "        label=\"Logit\"\n",
    "    )\n",
    "\n",
    "    distress_years = tmp.loc[tmp[TARGET_COL] == 1, \"year\"]\n",
    "\n",
    "    if not distress_years.empty:\n",
    "        ax.scatter(\n",
    "            distress_years,\n",
    "            np.ones(len(distress_years)),\n",
    "            marker=\"x\",\n",
    "            s=45,\n",
    "            label=\"Realized distress\"\n",
    "        )\n",
    "\n",
    "    ax.set_title(country, fontsize=10)\n",
    "    ax.set_xlabel(\"Year\", fontsize=8)\n",
    "    ax.set_ylabel(\"Probability\", fontsize=8)\n",
    "    ax.set_ylim(0, 1.05)\n",
    "\n",
    "    # Integer year ticks only\n",
    "    ax.set_xticks(tmp[\"year\"].unique())\n",
    "    ax.set_xticklabels(tmp[\"year\"].unique().astype(int))\n",
    "\n",
    "    ax.grid(alpha=0.3)\n",
    "\n",
    "    ax.tick_params(\n",
    "        axis=\"x\",\n",
    "        rotation=45,\n",
    "        labelsize=7\n",
    "    )\n",
    "\n",
    "    ax.tick_params(\n",
    "        axis=\"y\",\n",
    "        labelsize=7\n",
    "    )\n",
    "\n",
    "# Remove unused axes\n",
    "for ax in axes[len(countries):]:\n",
    "    ax.remove()\n",
    "\n",
    "handles, labels = axes[0].get_legend_handles_labels()\n",
    "\n",
    "fig.legend(\n",
    "    handles,\n",
    "    labels,\n",
    "    loc=\"lower center\",\n",
    "    ncol=4,\n",
    "    fontsize=8,\n",
    "    frameon=False\n",
    ")\n",
    "\n",
    "fig.suptitle(\n",
    "    \"Predicted Probability and Realized Distress by Country\",\n",
    "    fontsize=12\n",
    ")\n",
    "\n",
    "plt.tight_layout(rect=[0, 0.05, 1, 0.95])\n",
    "\n",
    "country_path = os.path.join(\n",
    "    FIG_DIR,\n",
    "    \"country_probability_trajectories.png\"\n",
    ")\n",
    "\n",
    "plt.savefig(\n",
    "    country_path,\n",
    "    dpi=300,\n",
    "    bbox_inches=\"tight\"\n",
    ")\n",
    "\n",
    "plt.close(fig)\n",
    "\n",
    "print(f\"Country-level probability trajectories saved to: {country_path}\")\n",
    "\n",
    "\n",
    "# =========================================================\n",
    "# POOLED PROBABILITY SIGNALS OVER TIME (APPENDIX)\n",
    "# =========================================================\n",
    "\n",
    "# Ensure integer year\n",
    "oos_preds[\"year\"] = oos_preds[\"year\"].astype(int)\n",
    "\n",
    "# Aggregate yearly averages\n",
    "pooled = (\n",
    "    oos_preds.groupby(\"year\", as_index=False)\n",
    "    .agg({\n",
    "        \"p_struct\": \"mean\",\n",
    "        \"p_hybrid_cv\": \"mean\",\n",
    "        \"p_logit\": \"mean\",\n",
    "        TARGET_COL: \"mean\",\n",
    "    })\n",
    "    .sort_values(\"year\")\n",
    ")\n",
    "\n",
    "# Ensure integer years\n",
    "pooled[\"year\"] = pooled[\"year\"].astype(int)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8, 5))\n",
    "\n",
    "# Structural\n",
    "ax.plot(\n",
    "    pooled[\"year\"],\n",
    "    pooled[\"p_struct\"],\n",
    "    marker=\"o\",\n",
    "    linewidth=2,\n",
    "    label=\"Structural\"\n",
    ")\n",
    "\n",
    "# Hybrid\n",
    "ax.plot(\n",
    "    pooled[\"year\"],\n",
    "    pooled[\"p_hybrid_cv\"],\n",
    "    marker=\"o\",\n",
    "    linewidth=2,\n",
    "    label=\"Hybrid\"\n",
    ")\n",
    "\n",
    "# Logit\n",
    "ax.plot(\n",
    "    pooled[\"year\"],\n",
    "    pooled[\"p_logit\"],\n",
    "    marker=\"o\",\n",
    "    linewidth=2,\n",
    "    label=\"Logit\"\n",
    ")\n",
    "\n",
    "# Realized distress frequency\n",
    "ax.plot(\n",
    "    pooled[\"year\"],\n",
    "    pooled[TARGET_COL],\n",
    "    marker=\"x\",\n",
    "    linestyle=\"--\",\n",
    "    linewidth=1.5,\n",
    "    markersize=7,\n",
    "    label=\"Realized distress frequency\"\n",
    ")\n",
    "\n",
    "# Force integer year ticks\n",
    "ax.set_xticks(pooled[\"year\"].unique())\n",
    "ax.set_xticklabels(\n",
    "    pooled[\"year\"].unique().astype(int),\n",
    "    rotation=45\n",
    ")\n",
    "\n",
    "ax.set_xlabel(\"Year\")\n",
    "ax.set_ylabel(\"Average probability / distress frequency\")\n",
    "\n",
    "ax.set_title(\n",
    "    \"Pooled Probability Signals and Realized Distress Over Time\"\n",
    ")\n",
    "\n",
    "ax.set_ylim(0, 1.05)\n",
    "ax.grid(alpha=0.3)\n",
    "\n",
    "ax.legend(\n",
    "    fontsize=8,\n",
    "    loc=\"best\"\n",
    ")\n",
    "\n",
    "plt.tight_layout()\n",
    "\n",
    "pooled_path = os.path.join(\n",
    "    FIG_DIR,\n",
    "    \"appendix_pooled_probability_signals.png\"\n",
    ")\n",
    "\n",
    "plt.savefig(\n",
    "    pooled_path,\n",
    "    dpi=300,\n",
    "    bbox_inches=\"tight\"\n",
    ")\n",
    "\n",
    "plt.close(fig)\n",
    "\n",
    "print(f\"Pooled probability signals figure saved to: {pooled_path}\")\n",
    "\n",
    "# =========================================================\n",
    "# SAVE BOOTSTRAP MEAN DIFFERENCE TABLE\n",
    "# =========================================================\n",
    "\n",
    "# Round for publication formatting\n",
    "bootstrap_table_final = bootstrap_table.copy()\n",
    "\n",
    "bootstrap_table_final[\"Mean Diff.\"] = (\n",
    "    bootstrap_table_final[\"Mean Diff.\"].round(3)\n",
    ")\n",
    "\n",
    "bootstrap_table_final[\"Lower CI\"] = (\n",
    "    bootstrap_table_final[\"Lower CI\"].round(3)\n",
    ")\n",
    "\n",
    "bootstrap_table_final[\"Upper CI\"] = (\n",
    "    bootstrap_table_final[\"Upper CI\"].round(3)\n",
    ")\n",
    "\n",
    "print(\"\\n=== FINAL BOOTSTRAP AUC DIFFERENCE TABLE ===\")\n",
    "print(bootstrap_table_final.to_string(index=False))\n",
    "\n",
    "# Save CSV\n",
    "bootstrap_path = os.path.join(\n",
    "    OUTPUT_DIR,\n",
    "    \"bootstrap_auc_mean_differences.csv\"\n",
    ")\n",
    "\n",
    "bootstrap_table_final.to_csv(\n",
    "    bootstrap_path,\n",
    "    index=False\n",
    ")\n",
    "\n",
    "print(f\"Bootstrap mean-difference table saved to: {bootstrap_path}\")\n",
    "\n",
    "print(\"\\nReplication script completed successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3808793d-d40b-451f-b0ec-72d786ab4106",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
